export default function Footer() {
  return (
    <footer className="border-t border-border mt-16">
      <div className="max-w-6xl mx-auto px-8 py-8">
        <p className="text-xs text-faint leading-relaxed max-w-2xl mb-2">
          Story summaries are generated by Claude from source reporting.
          Verify important details against the original source before
          citing.
        </p>
        <p className="text-xs text-faint leading-relaxed max-w-2xl mb-4">
          Some story images are placeholder photography from{" "}
          <a
            href="https://www.pexels.com"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-muted transition"
          >
            Pexels
          </a>
          , used when a story has no original source image.
        </p>
        <div className="flex items-center justify-between text-xs font-mono text-faint">
          <span>© {new Date().getFullYear()} Axonix</span>
          <a
            href="https://prateekbatra.dev"
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-foreground transition"
          >
            Built by Prateek Batra
          </a>
        </div>
      </div>
    </footer>
  );
}